function mu_ast = find_mu(params,m,L)
% (exp(mu_k) <= exp(mu_k(3,3))) .* (mu_k<0)
% gam=0.7; aa = (1+kx+ky).^q ./ abs(mu_k).^(gam); aa(1:3,1:3)=0;Cgam = max(max(aa)), [mmax1,mmax2] = find(aa == max(max(aa))),Cgam*(gam/exp(1)/0.9)^gam
% gam=0.6; aa = bkL2 ./ abs(mu_k).^(gam); aa(1:3,1:3)=0;Cgam = max(max(aa)), [mmax1,mmax2] = find(aa == max(max(aa))),Cgam*(gam/exp(1)/0.5)^gam
%
% q = 2;
sigma   = params(2);
epsilon = params(3);
% 
m1 = m(1); m2 = m(2);
N1 = 30; N2 = 30;
L1 = L(1); L2 = L(2);
%
[kx,ky] = ndgrid(0:N1-1,0:N2-1);
%
bkL2 = (kx*L1).^2 + (ky*L2).^2;
mu_k = bkL2 .* (-epsilon^2*bkL2 + 1) - sigma;
% 
mu_k(1:m1,1:m2) = 1.1 * min(mu_k,[],'all');
if all(mu_k(:)<0)
  mu_ast = max(mu_k,[],'all');
else
  mu_ast = NaN;
end
% 
% f = (1+kx+ky).^q .* exp(mu_k*t);
% f = exp(mu_k); % Semigroup estimate generated by mu_k
% 
% [m1,m2]=find(f==max(max(f)));
% %
% m = [m1,m2];
% end